### ISSUE TITLE
No source code in the repo

### ISSUE THREAD

**Issue by junghans** [moradza/VOTCA_CRE#1]
Looking at https://github.com/moradza/VOTCA_CRE/tree/master/src there seems to be no code in the repo

Related to votca/csg#199

**Comment by moradza** [comment]
Uploaded the src file as a *.rar file.  Furthermore, main files are now available through csg_cre.

**Comment by junghans** [comment]
17.5 MB that is more than all votca modules combined, you really should strip the binaries out of the rar. Plus, adding a compressed archive to git is very bad practice to start with, it hinders user to browse the code with github.

And VOTCA is license under Apache-2.0, so make sure you fulfill the license's attribution notice requirements in your code, i.e. create a `NOTICE` file listing all the codes your work is derived from.

**Comment by moradza** [comment]
Sure, I deleted the rare file. I am kinda busy and my work is not anymore related to VOTCA package, so I don't support this code anymore or at least for a while.

**Comment by junghans** [comment]
That is ok, but you listed this place as a reference in your paper, so the code should be somewhere. 

And you should add a statement like "this code is derived from the original VOTCA source code vX.X licensed under Apacche-2.0 license, which can be found at www.votca.org" and please remove "you should contact votca support team for any information" from `NOTICE`, because we don't have the manpower to support your modifications either.

**Comment by moradza** [comment]
I put the code under csg_cre, I will replace the files in the repository with a clean version.
I added the statement above.
